### ISSUE TITLE
IMPORT ERROR: undefined symbol

### ISSUE THREAD

**Issue by MalikTeng** [masadcv/FastGeodis#39] opened 2023-02-11 19:42 UTC
**Describe the bug**
Hi, I have the following error when trying to import FastGeodis for my project,

`
Exception has occurred: ImportError

/home/***/anaconda3/envs/torch/lib/python3.9/site-packages/FastGeodisCpp.cpython-39-x86_64-linux-gnu.so: undefined symbol: 
_ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

  File "/home/***/Documents/***/model/networks.py", line 40, in <module>

    import FastGeodis

  File "/home/***/Documents/***/run_***.py", line 55, in <module>

    from model.networks import *

  File "/home/***/Documents/***/main.py", line 81, in <module>

    from run_*** import *

ImportError: /home/***/anaconda3/envs/torch/lib/python3.9/site-packages/FastGeodisCpp.cpython-39-x86_64-linux-gnu.so: undefined symbol: 
_ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2
`

**Desktop**
 - OS: Ubuntu
 - Version 18.04

**Environment**
 - Python 3.9.13
 - Pytorch 1.12.1
 - CUDA 11.3.1
 - GCC 7.5.0

**Additional context**
I have the same issue when trying to compile the cpp and cu files locally.

**Comment by MalikTeng** [comment] 2023-02-12 14:19
Issue fixed by creating another virtual environment with python 3.8.*. 

Not sure particularly what's going wrong.

**Comment by masadcv** [comment] 2023-02-14 21:24
It seems the issue is related to your setup. 
Can you try again with a new python3.9 virtual environment?

Since the issue was reported as fixed, I am closing this. Feel free to reopen if issue persists.

**Closed by masadcv** 2023-02-14 21:24 UTC
